In [1]:
import numpy as np

square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]])

print(square)

[[16  3  2 13]
 [ 5 10 11  8]
 [ 9  6  7 12]
 [ 4 15 14  1]]


In [4]:
print(square[0, 1])
print(square[3, 3])

3
1


In [7]:
print(square[0:2, 0:1])

[[16]
 [ 5]]


In [15]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(type(mylist))
print(mylist[3])

<class 'list'>
4


In [10]:
mylist1 = [[1, 2, 3], 
           [4, 5, 6], 
           [7, 8, 9]]
print(mylist1)
print(type(mylist1))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [13]:
print(mylist1[0:2,1:2])

TypeError: list indices must be integers or slices, not tuple